"""empty message

Revision ID: 08f444007226
Revises: 76b0dcc7a060
Create Date: 2021-10-21 23:29:30.710812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f444007226'
down_revision = '76b0dcc7a060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('funcao',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('functions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['functions_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_column('user', 'cargo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cargo', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('funcao')
    op.drop_table('functions')
    # ### end Alembic commands ###
