"""empty message

Revision ID: 092ceb1293d1
Revises: c14cd2b8478e
Create Date: 2021-10-25 09:40:41.689814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092ceb1293d1'
down_revision = 'c14cd2b8478e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postagem', sa.Column('papel_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'postagem', type_='foreignkey')
    op.create_foreign_key(None, 'postagem', 'papel', ['papel_id'], ['id'])
    op.drop_column('postagem', 'user_id')
    op.drop_column('postagem', 'recebido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postagem', sa.Column('recebido', sa.VARCHAR(), nullable=False))
    op.add_column('postagem', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'postagem', type_='foreignkey')
    op.create_foreign_key(None, 'postagem', 'user', ['user_id'], ['id'])
    op.drop_column('postagem', 'papel_id')
    # ### end Alembic commands ###
