"""empty message

Revision ID: 236635d871a8
Revises: 7cb8c21d6884
Create Date: 2021-10-21 14:23:59.752892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236635d871a8'
down_revision = '7cb8c21d6884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'cargo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cargo', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('area')
    # ### end Alembic commands ###
