"""empty message

Revision ID: 387563868fc1
Revises: 092ceb1293d1
Create Date: 2021-10-25 09:40:58.717872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387563868fc1'
down_revision = '092ceb1293d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'postagem', type_='foreignkey')
    op.create_foreign_key(None, 'postagem', 'papel', ['papel_id'], ['id'])
    op.drop_column('postagem', 'recebido')
    op.drop_column('postagem', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postagem', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('postagem', sa.Column('recebido', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'postagem', type_='foreignkey')
    op.create_foreign_key(None, 'postagem', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
