"""empty message

Revision ID: 3c02a98bdbc9
Revises: a2ed9db22b7a
Create Date: 2021-10-23 23:41:55.839317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c02a98bdbc9'
down_revision = 'a2ed9db22b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('functions')
    op.drop_table('postagem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assunto', sa.VARCHAR(), nullable=False),
    sa.Column('remetente', sa.VARCHAR(), nullable=False),
    sa.Column('recebido', sa.VARCHAR(), nullable=False),
    sa.Column('texto', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('cpf', sa.INTEGER(), nullable=False),
    sa.Column('ra', sa.INTEGER(), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=False),
    sa.Column('envia', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
