"""empty message

Revision ID: 491d9ea028e8
Revises: 5f29b2fdde50
Create Date: 2021-10-19 16:38:16.665560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491d9ea028e8'
down_revision = '5f29b2fdde50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('areas_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'areas', ['areas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'areas_id')
    # ### end Alembic commands ###
