"""empty message

Revision ID: 632bc51123e6
Revises: 1521d624ede9
Create Date: 2021-10-21 17:49:14.675122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632bc51123e6'
down_revision = '1521d624ede9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('area', sa.String(length=100), nullable=True))
    op.drop_column('function', 'nome_da_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('nome_da_area', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('function', 'area')
    # ### end Alembic commands ###
