"""empty message

Revision ID: 705afb586253
Revises: 73890f6b2113
Create Date: 2021-10-19 21:31:39.312979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705afb586253'
down_revision = '73890f6b2113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
