"""empty message

Revision ID: 72afdcc79ac9
Revises: 491d9ea028e8
Create Date: 2021-10-19 19:49:27.188494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72afdcc79ac9'
down_revision = '491d9ea028e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('areas_user', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
