"""empty message

Revision ID: 73890f6b2113
Revises: 72afdcc79ac9
Create Date: 2021-10-19 21:05:33.315317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73890f6b2113'
down_revision = '72afdcc79ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
