"""empty message

Revision ID: 7624a880d9d9
Revises: 97dd75a96812
Create Date: 2021-10-21 15:39:20.773729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7624a880d9d9'
down_revision = '97dd75a96812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cargo', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cargo')
    # ### end Alembic commands ###
