"""empty message

Revision ID: 76b0dcc7a060
Revises: eb40d1a5b17c
Create Date: 2021-10-21 20:30:01.011617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b0dcc7a060'
down_revision = 'eb40d1a5b17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('envia', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assunto', sa.String(), nullable=False),
    sa.Column('remetente', sa.String(), nullable=False),
    sa.Column('recebido', sa.String(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('color_association')
    op.drop_table('cards')
    op.drop_table('colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_association',
    sa.Column('card_id', sa.INTEGER(), nullable=False),
    sa.Column('color_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'color_id')
    )
    op.drop_table('postagem')
    op.drop_table('user')
    # ### end Alembic commands ###
