"""empty message

Revision ID: 796319e66add
Revises: 1a7d6a2ab228
Create Date: 2021-10-19 15:49:00.264993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796319e66add'
down_revision = '1a7d6a2ab228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'cargo')
    op.add_column('user', sa.Column('cargo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cargo')
    op.add_column('area', sa.Column('cargo', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
