"""empty message

Revision ID: 7e35660351ef
Revises: d2d7c1c5d3da
Create Date: 2021-10-24 00:00:50.748658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e35660351ef'
down_revision = 'd2d7c1c5d3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papel_nome', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('papel_nome')
    )
    op.drop_table('student')
    op.drop_table('teacher')
    op.add_column('association', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('association', sa.Column('papel_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'association', 'papel', ['papel_id'], ['id'])
    op.drop_column('association', 'student_id')
    op.drop_column('association', 'teacher_id')
    op.add_column('user', sa.Column('nome_usuario', sa.String(length=70), nullable=True))
    op.add_column('user', sa.Column('email_usuario', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'user', ['nome_usuario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email_usuario')
    op.drop_column('user', 'nome_usuario')
    op.add_column('association', sa.Column('teacher_id', sa.INTEGER(), nullable=True))
    op.add_column('association', sa.Column('student_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'teacher', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'association', 'student', ['student_id'], ['id'])
    op.drop_column('association', 'papel_id')
    op.drop_column('association', 'user_id')
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=True),
    sa.Column('office', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('papel')
    # ### end Alembic commands ###
