"""empty message

Revision ID: 8119cea91c8f
Revises: 34c57214a046
Create Date: 2021-10-19 23:42:54.163865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8119cea91c8f'
down_revision = '34c57214a046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'area', ['area_id'], ['id'])
    op.drop_column('user', 'cargo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cargo', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
