"""empty message

Revision ID: 835f0603e229
Revises: ea33c1f6a970
Create Date: 2021-10-21 14:58:41.596798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835f0603e229'
down_revision = 'ea33c1f6a970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('user_nome', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.create_foreign_key(None, 'area', 'user', ['user_nome'], ['nome'])
    op.drop_column('area', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.create_foreign_key(None, 'area', 'user', ['user_id'], ['id'])
    op.drop_column('area', 'user_nome')
    # ### end Alembic commands ###
