"""empty message

Revision ID: 92e5392c05ef
Revises: a36a1583a85e
Create Date: 2021-10-31 13:21:04.288338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e5392c05ef'
down_revision = 'a36a1583a85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmado', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmado')
    # ### end Alembic commands ###
