"""empty message

Revision ID: 97dd75a96812
Revises: a57018c7e3ea
Create Date: 2021-10-21 15:02:07.652384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dd75a96812'
down_revision = 'a57018c7e3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'user_nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('user_nome', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
