"""empty message

Revision ID: a2ed9db22b7a
Revises: db6ab8709e0a
Create Date: 2021-10-21 23:36:01.766485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ed9db22b7a'
down_revision = 'db6ab8709e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcao')
    op.add_column('functions', sa.Column('cargo', sa.String(length=100), nullable=True))
    op.add_column('functions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'functions', 'user', ['user_id'], ['id'])
    op.drop_column('functions', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('name', sa.VARCHAR(length=70), nullable=True))
    op.drop_constraint(None, 'functions', type_='foreignkey')
    op.drop_column('functions', 'user_id')
    op.drop_column('functions', 'cargo')
    op.create_table('funcao',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('functions_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['functions_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
