"""empty message

Revision ID: a36a1583a85e
Revises: 387563868fc1
Create Date: 2021-10-25 11:23:05.791190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36a1583a85e'
down_revision = '387563868fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_papel',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('papel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('postagem_papel',
    sa.Column('postagem_id', sa.Integer(), nullable=True),
    sa.Column('papel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['postagem_id'], ['postagem.id'], )
    )
    op.drop_table('association')
    op.add_column('papel', sa.Column('nome', sa.String(length=150), nullable=False))
    op.add_column('papel', sa.Column('pode_editar', sa.Boolean(), nullable=True))
    op.add_column('papel', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'papel', ['nome'])
    op.drop_column('papel', 'papel_nome')
    op.add_column('postagem', sa.Column('titulo', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'postagem', ['titulo'])
    op.create_unique_constraint(None, 'postagem', ['texto'])
    op.drop_constraint(None, 'postagem', type_='foreignkey')
    op.drop_column('postagem', 'data')
    op.drop_column('postagem', 'papel_id')
    op.drop_column('postagem', 'assunto')
    op.drop_column('postagem', 'remetente')
    op.alter_column('user', 'cpf',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['senha'])
    op.create_unique_constraint(None, 'user', ['nome'])
    op.drop_column('user', 'ra')
    op.drop_column('user', 'envia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('envia', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('ra', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'cpf',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('postagem', sa.Column('remetente', sa.VARCHAR(), nullable=False))
    op.add_column('postagem', sa.Column('assunto', sa.VARCHAR(), nullable=False))
    op.add_column('postagem', sa.Column('papel_id', sa.INTEGER(), nullable=True))
    op.add_column('postagem', sa.Column('data', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'postagem', 'papel', ['papel_id'], ['id'])
    op.drop_constraint(None, 'postagem', type_='unique')
    op.drop_constraint(None, 'postagem', type_='unique')
    op.drop_column('postagem', 'titulo')
    op.add_column('papel', sa.Column('papel_nome', sa.VARCHAR(length=70), nullable=True))
    op.drop_constraint(None, 'papel', type_='unique')
    op.drop_column('papel', 'admin')
    op.drop_column('papel', 'pode_editar')
    op.drop_column('papel', 'nome')
    op.create_table('association',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('papel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['papel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('postagem_papel')
    op.drop_table('user_papel')
    # ### end Alembic commands ###
