"""empty message

Revision ID: ea33c1f6a970
Revises: 89e82bca8c2c
Create Date: 2021-10-21 14:50:22.772284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea33c1f6a970'
down_revision = '89e82bca8c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.create_foreign_key(None, 'area', 'user', ['user_id'], ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.create_foreign_key(None, 'area', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
